# Generated by Django 3.2.7 on 2021-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('polls', models.ManyToManyField(to='asks.Survey')),
                ('question', models.ManyToManyField(to='asks.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('creator', models.CharField(max_length=128)),
                ('code', models.PositiveIntegerField()),
                ('password_admin', models.CharField(max_length=128)),
                ('themes', models.ManyToManyField(to='room.Theme')),
            ],
        ),
    ]
