# Generated by Django 3.2.7 on 2021-10-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
