# Generated by Django 3.2.7 on 2021-10-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='themes',
            field=models.ManyToManyField(blank=True, to='room.Theme'),
        ),
    ]
