# Generated by Django 3.2.7 on 2021-10-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0002_auto_20211002_1924'),
        ('room', '0003_alter_room_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='polls',
            field=models.ManyToManyField(blank=True, to='asks.Survey'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='question',
            field=models.ManyToManyField(blank=True, to='asks.Question'),
        ),
    ]
