# Generated by Django 3.2.7 on 2021-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20211013_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='question',
            new_name='questions',
        ),
        migrations.AddField(
            model_name='room',
            name='creator',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='theme',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='creator',
            field=models.CharField(default='', max_length=128),
        ),
    ]
