# Generated by Django 3.2.7 on 2021-10-22 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_remove_theme_polls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='questions',
        ),
        migrations.AddField(
            model_name='theme',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='room.room'),
        ),
    ]
