# Generated by Django 3.2.7 on 2021-10-24 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20211021_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AddField(
            model_name='room',
            name='visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.CharField(default='', max_length=128, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='room',
            name='password_admin',
            field=models.CharField(default='admin', max_length=128, verbose_name='Senha de administrador'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='creator',
            field=models.CharField(default='', max_length=128, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='room.room', verbose_name='Sala'),
        ),
    ]
