# Generated by Django 3.2.7 on 2021-11-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_auto_20211023_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password_admin',
            field=models.CharField(default='admin', max_length=128, verbose_name='Senha de moderador(encriptada)'),
        ),
    ]
