# Generated by Django 3.2.7 on 2021-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('text', models.TextField(max_length=400)),
                ('answered', models.BooleanField(default=False)),
                ('alteration', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(blank=True, max_length=255)),
                ('option_4', models.CharField(blank=True, max_length=255)),
                ('option_5', models.CharField(blank=True, max_length=255)),
                ('correct_option', models.CharField(blank=True, max_length=255)),
                ('finalized', models.BooleanField(default=False)),
            ],
        ),
    ]
