# Generated by Django 3.2.7 on 2021-10-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('percent', models.PositiveIntegerField(blank=True)),
                ('correct', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='option_5',
        ),
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='survey',
            name='options',
            field=models.ManyToManyField(blank=True, to='asks.Option'),
        ),
    ]
