# Generated by Django 3.2.7 on 2021-10-13 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0002_auto_20211002_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='percent',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='option',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='alteration',
        ),
        migrations.RemoveField(
            model_name='question',
            name='username',
        ),
        migrations.AddField(
            model_name='question',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='question',
            name='down_votes',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='up_votes',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
