# Generated by Django 3.2.7 on 2021-10-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0003_auto_20211013_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creator',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='down_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='up_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
