# Generated by Django 3.2.7 on 2021-10-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_remove_theme_polls'),
        ('asks', '0005_question_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='options',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
