# Generated by Django 3.2.7 on 2021-10-22 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20211021_2149'),
        ('asks', '0006_auto_20211019_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='room.theme'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=512),
        ),
    ]
