# Generated by Django 3.2.7 on 2021-11-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_room_password_admin'),
        ('asks', '0008_auto_20211023_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=550, verbose_name='Chave de usuário')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keys', to='room.room', verbose_name='Sala')),
            ],
        ),
        migrations.CreateModel(
            name='AdminKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=550, verbose_name='Chave de admin')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_keys', to='room.room', verbose_name='Sala')),
            ],
        ),
    ]
