# Generated by Django 3.2.7 on 2021-11-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0009_adminkey_userkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.ManyToManyField(null=True, to='asks.UserKey', verbose_name='Chaves usadas por usuários')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='used_keys', to='asks.question', verbose_name='Pergunta')),
            ],
        ),
    ]
