# Generated by Django 3.2.7 on 2021-11-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0010_usedkeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedkeys',
            name='keys',
            field=models.ManyToManyField(blank=True, null=True, to='asks.UserKey', verbose_name='Chaves usadas por usuários'),
        ),
    ]
