# Generated by Django 3.2.7 on 2021-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0011_alter_usedkeys_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedkeys',
            name='keys',
            field=models.ManyToManyField(to='asks.UserKey', verbose_name='Chaves usadas por usuários para manipular contagem de votos'),
        ),
    ]
