# Generated by Django 3.2.7 on 2021-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0014_alter_usedkeys_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminkey',
            options={'verbose_name': 'Chave de administrador', 'verbose_name_plural': 'Chave de administradores'},
        ),
        migrations.AlterModelOptions(
            name='usedkeys',
            options={'verbose_name': 'Chaves usadas', 'verbose_name_plural': 'Chaves usadas'},
        ),
        migrations.AlterModelOptions(
            name='userkey',
            options={'verbose_name': 'Chave de usuário', 'verbose_name_plural': 'Chave de usuários'},
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='usedkeys',
            name='keys',
            field=models.ManyToManyField(to='asks.UserKey', verbose_name='Chaves usadas'),
        ),
    ]
